# config/routes.yaml

app_login:
    path: /
    controller: App\Controller\SecurityController::login
app_home:
    path: /home
    controller: App\Controller\HomeController::home    
app_register:
    path: /register
    controller: App\Controller\RegistrationController::register
app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout
app_evenement_index:
    path: /evenement/index
    controller: App\Controller\EvenementController::index

app_evenement_new:
    path: /evenement/new
    controller: App\Controller\EvenementController::new

app_evenement_edit:
    path: /evenement/{id}/edit  # Inclure {id} dans le chemin
    controller: App\Controller\EvenementController::edit

app_evenement_delete:
    path: /evenement/{id}/delete  # Inclure {id} dans le chemin
    controller: App\Controller\EvenementController::delete

app_evenement_show:
    path: /evenement/{id}  # Inclure {id} dans le chemin
    controller: App\Controller\EvenementController::show
app_users_list:
    path: /liste
    controller: App\Controller\UserController::list

# Liste des inscriptions pour un événement (ou pour tous les événements)
app_inscription_my:
    path: /mesInscriptions
    controller: App\Controller\InscriptionController::myInscription

# Liste des inscriptions pour un événement (ou pour tous les événements)
app_inscription_index:
    path: /inscription
    controller: App\Controller\InscriptionController::index

# Créer une nouvelle inscription
app_inscription_new:
    path: /inscription/new
    controller: App\Controller\InscriptionController::new

# Afficher une inscription spécifique
app_inscription_show:
    path: /inscription/{id}  # Inclure {id} dans le chemin
    controller: App\Controller\InscriptionController::show

# Modifier une inscription existante
app_inscription_edit:
    path: /inscription/{id}/edit  # Inclure {id} dans le chemin
    controller: App\Controller\InscriptionController::edit

# Supprimer une inscription
app_inscription_delete:
    path: /inscription/{id}/delete  # Inclure {id} dans le chemin
    controller: App\Controller\InscriptionController::delete
